// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_finanzas_grupo5.Data;

#nullable disable

namespace backend_finanzas_grupo5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend_finanzas_grupo5.Models.CronogramaPago", b =>
                {
                    b.Property<int>("IdCronograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AmoPeriodo")
                        .HasColumnType("double");

                    b.Property<double>("CuoMensual")
                        .HasColumnType("double");

                    b.Property<int>("IdSimulacion")
                        .HasColumnType("int");

                    b.Property<double>("IntPeriodo")
                        .HasColumnType("double");

                    b.Property<double?>("InteresCapitalizado")
                        .HasColumnType("double");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<double?>("MontoBalonPagado")
                        .HasColumnType("double");

                    b.Property<double>("PagoTotal")
                        .HasColumnType("double");

                    b.Property<double>("SaldoFinal")
                        .HasColumnType("double");

                    b.Property<double>("SaldoInicial")
                        .HasColumnType("double");

                    b.Property<double>("SegDesMonto")
                        .HasColumnType("double");

                    b.Property<double>("SegVehMonto")
                        .HasColumnType("double");

                    b.Property<string>("TipoCuota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCronograma");

                    b.HasIndex("IdSimulacion", "Mes")
                        .IsUnique();

                    b.ToTable("CronogramaPagos");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.ResultadoSimulacion", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdSimulacion")
                        .HasColumnType("int");

                    b.Property<double>("MonInteresTot")
                        .HasColumnType("double");

                    b.Property<double>("MonSeguroTot")
                        .HasColumnType("double");

                    b.Property<double>("MontoCuotaBalon")
                        .HasColumnType("double");

                    b.Property<double>("MontoTotalFin")
                        .HasColumnType("double");

                    b.Property<double>("Tem")
                        .HasColumnType("double");

                    b.Property<double>("ValTcea")
                        .HasColumnType("double");

                    b.Property<double>("ValTir")
                        .HasColumnType("double");

                    b.Property<double>("ValVan")
                        .HasColumnType("double");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdSimulacion")
                        .IsUnique();

                    b.ToTable("ResultadosSimulacion");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Simulacion", b =>
                {
                    b.Property<int>("IdSimulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ComPortes")
                        .HasColumnType("double");

                    b.Property<double>("FinBalonPorc")
                        .HasColumnType("double");

                    b.Property<DateTime>("FinFecInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("FinIniMonto")
                        .HasColumnType("double");

                    b.Property<int>("FinPlazo")
                        .HasColumnType("int");

                    b.Property<int>("GraMeses")
                        .HasColumnType("int");

                    b.Property<string>("GraTipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<double>("SegDesgrav")
                        .HasColumnType("double");

                    b.Property<double>("SegVehic")
                        .HasColumnType("double");

                    b.Property<string>("TasaCapit")
                        .HasColumnType("longtext");

                    b.Property<string>("TasaTipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TasaValor")
                        .HasColumnType("double");

                    b.Property<double>("ValCok")
                        .HasColumnType("double");

                    b.HasKey("IdSimulacion");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UsuApellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuCorreo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuDni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuNumero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("UsuPerfilSe")
                        .HasColumnType("double");

                    b.HasKey("IdUsuario");

                    b.HasIndex("UsuCorreo")
                        .IsUnique();

                    b.HasIndex("UsuDni")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("VehImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("VehMarca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VehModelo")
                        .HasColumnType("longtext");

                    b.Property<string>("VehMoneda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("VehPrecio")
                        .HasColumnType("double");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.CronogramaPago", b =>
                {
                    b.HasOne("backend_finanzas_grupo5.Models.Simulacion", "Simulacion")
                        .WithMany("CronogramaPagos")
                        .HasForeignKey("IdSimulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.ResultadoSimulacion", b =>
                {
                    b.HasOne("backend_finanzas_grupo5.Models.Simulacion", "Simulacion")
                        .WithOne("ResultadoSimulacion")
                        .HasForeignKey("backend_finanzas_grupo5.Models.ResultadoSimulacion", "IdSimulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Simulacion", b =>
                {
                    b.HasOne("backend_finanzas_grupo5.Models.Usuario", "Usuario")
                        .WithMany("Simulaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_finanzas_grupo5.Models.Vehiculo", "Vehiculo")
                        .WithMany("Simulaciones")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Simulacion", b =>
                {
                    b.Navigation("CronogramaPagos");

                    b.Navigation("ResultadoSimulacion");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Usuario", b =>
                {
                    b.Navigation("Simulaciones");
                });

            modelBuilder.Entity("backend_finanzas_grupo5.Models.Vehiculo", b =>
                {
                    b.Navigation("Simulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
